"""empty message

Revision ID: 2e5a3c5e288a
Revises: 886380a53c3a
Create Date: 2020-07-11 08:18:51.365312

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e5a3c5e288a'
down_revision = '886380a53c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user', 'last_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    # ### end Alembic commands ###
