"""empty message

Revision ID: 802eae9ffcf7
Revises: 
Create Date: 2020-08-04 11:51:33.316755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802eae9ffcf7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('form', sa.Column('dedication', sa.Float(), nullable=False))
    op.add_column('form', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'form', 'goals', ['goal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'form', type_='foreignkey')
    op.drop_column('form', 'goal_id')
    op.drop_column('form', 'dedication')
    op.drop_table('goals')
    # ### end Alembic commands ###
